// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftControllerManagerConfig) DeepCopyInto(out *OpenShiftControllerManagerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftControllerManagerConfig.
func (in *OpenShiftControllerManagerConfig) DeepCopy() *OpenShiftControllerManagerConfig {
	if in == nil {
		return nil
	}
	out := new(OpenShiftControllerManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftControllerManagerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftControllerManagerOperatorConfig) DeepCopyInto(out *OpenShiftControllerManagerOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftControllerManagerOperatorConfig.
func (in *OpenShiftControllerManagerOperatorConfig) DeepCopy() *OpenShiftControllerManagerOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OpenShiftControllerManagerOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftControllerManagerOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftControllerManagerOperatorConfigList) DeepCopyInto(out *OpenShiftControllerManagerOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenShiftControllerManagerOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftControllerManagerOperatorConfigList.
func (in *OpenShiftControllerManagerOperatorConfigList) DeepCopy() *OpenShiftControllerManagerOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(OpenShiftControllerManagerOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftControllerManagerOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftControllerManagerOperatorConfigSpec) DeepCopyInto(out *OpenShiftControllerManagerOperatorConfigSpec) {
	*out = *in
	out.OperatorSpec = in.OperatorSpec
	in.UserConfig.DeepCopyInto(&out.UserConfig)
	in.ObservedConfig.DeepCopyInto(&out.ObservedConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftControllerManagerOperatorConfigSpec.
func (in *OpenShiftControllerManagerOperatorConfigSpec) DeepCopy() *OpenShiftControllerManagerOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OpenShiftControllerManagerOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftControllerManagerOperatorConfigStatus) DeepCopyInto(out *OpenShiftControllerManagerOperatorConfigStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftControllerManagerOperatorConfigStatus.
func (in *OpenShiftControllerManagerOperatorConfigStatus) DeepCopy() *OpenShiftControllerManagerOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OpenShiftControllerManagerOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}
