apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:templateinstance-impersonation
rules:
- apiGroups:
  - template.openshift.io
  resources:
  - templateinstances
  verbs:
  - assign
