apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:openshift-controller-manager:leader-locking-ingress-to-route-controller
  namespace: openshift-route-controller-manager
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - create
  - update
