// Package v410_00_assets Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// bindata/v4.1.0/openshift-controller-manager/cm.yaml
// bindata/v4.1.0/openshift-controller-manager/defaultconfig.yaml
// bindata/v4.1.0/openshift-controller-manager/ds.yaml
// bindata/v4.1.0/openshift-controller-manager/informer-clusterrole.yaml
// bindata/v4.1.0/openshift-controller-manager/informer-clusterrolebinding.yaml
// bindata/v4.1.0/openshift-controller-manager/leader-role.yaml
// bindata/v4.1.0/openshift-controller-manager/leader-rolebinding.yaml
// bindata/v4.1.0/openshift-controller-manager/old-leader-role.yaml
// bindata/v4.1.0/openshift-controller-manager/old-leader-rolebinding.yaml
// bindata/v4.1.0/openshift-controller-manager/openshift-service-ca-cm.yaml
// bindata/v4.1.0/openshift-controller-manager/sa.yaml
// bindata/v4.1.0/openshift-controller-manager/separate-sa-role.yaml
// bindata/v4.1.0/openshift-controller-manager/separate-sa-rolebinding.yaml
// bindata/v4.1.0/openshift-controller-manager/servicemonitor-role.yaml
// bindata/v4.1.0/openshift-controller-manager/servicemonitor-rolebinding.yaml
// bindata/v4.1.0/openshift-controller-manager/svc.yaml
// bindata/v4.1.0/openshift-controller-manager/tokenreview-clusterrole.yaml
// bindata/v4.1.0/openshift-controller-manager/tokenreview-clusterrolebinding.yaml
package v410_00_assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// Mode return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _v410OpenshiftControllerManagerCmYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-controller-manager
  name: config
data:
  config.yaml:
`)

func v410OpenshiftControllerManagerCmYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerCmYaml, nil
}

func v410OpenshiftControllerManagerCmYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerDefaultconfigYaml = []byte(`apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftControllerManagerConfig
`)

func v410OpenshiftControllerManagerDefaultconfigYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerDefaultconfigYaml, nil
}

func v410OpenshiftControllerManagerDefaultconfigYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerDefaultconfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/defaultconfig.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerDsYaml = []byte(`apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: openshift-controller-manager
  name: controller-manager
  labels:
    app: openshift-controller-manager
    controller-manager: "true"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openshift-controller-manager
      controller-manager: "true"
  template:
    metadata:
      name: openshift-controller-manager
      labels:
        app: openshift-controller-manager
        controller-manager: "true"
    spec:
      priorityClassName: system-node-critical 
      serviceAccountName: openshift-controller-manager-sa
      containers:
      - name: controller-manager
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["hypershift", "openshift-controller-manager"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/configmaps/client-ca
          name: client-ca
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      volumes:
      - name: config
        configMap:
          name: config
      - name: client-ca
        configMap:
          name: client-ca
      - name: serving-cert
        secret:
          secretName: serving-cert
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - operator: Exists
`)

func v410OpenshiftControllerManagerDsYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerDsYaml, nil
}

func v410OpenshiftControllerManagerDsYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerDsYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/ds.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerInformerClusterroleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:openshift-controller-manager
rules:
# we run cluster resource quota, so we have to be able to see all resources
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
`)

func v410OpenshiftControllerManagerInformerClusterroleYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerInformerClusterroleYaml, nil
}

func v410OpenshiftControllerManagerInformerClusterroleYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerInformerClusterroleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/informer-clusterrole.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerInformerClusterrolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:openshift-controller-manager
roleRef:
  kind: ClusterRole
  name: system:openshift:openshift-controller-manager
subjects:
- kind: ServiceAccount
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
`)

func v410OpenshiftControllerManagerInformerClusterrolebindingYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerInformerClusterrolebindingYaml, nil
}

func v410OpenshiftControllerManagerInformerClusterrolebindingYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerInformerClusterrolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/informer-clusterrolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerLeaderRoleYaml = []byte(`# needed to get the legacy lock that we used to use
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:leader-locking-openshift-controller-manager
  namespace: openshift-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - openshift-master-controllers
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch
`)

func v410OpenshiftControllerManagerLeaderRoleYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerLeaderRoleYaml, nil
}

func v410OpenshiftControllerManagerLeaderRoleYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerLeaderRoleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/leader-role.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerLeaderRolebindingYaml = []byte(`# needed to get the legacy lock that we used to use
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-controller-manager
  name: system:openshift:leader-locking-openshift-controller-manager
roleRef:
  kind: Role
  name: system:openshift:leader-locking-openshift-controller-manager
subjects:
- kind: ServiceAccount
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
`)

func v410OpenshiftControllerManagerLeaderRolebindingYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerLeaderRolebindingYaml, nil
}

func v410OpenshiftControllerManagerLeaderRolebindingYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerLeaderRolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/leader-rolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerOldLeaderRoleYaml = []byte(`# needed to get the legacy lock that we used to use
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:leader-locking-openshift-controller-manager
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - openshift-master-controllers
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
  - patch`)

func v410OpenshiftControllerManagerOldLeaderRoleYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerOldLeaderRoleYaml, nil
}

func v410OpenshiftControllerManagerOldLeaderRoleYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerOldLeaderRoleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/old-leader-role.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerOldLeaderRolebindingYaml = []byte(`# needed to get the legacy lock that we used to use
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: system:openshift:leader-locking-openshift-controller-manager
roleRef:
  kind: Role
  name: system:openshift:leader-locking-openshift-controller-manager
subjects:
- kind: ServiceAccount
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
`)

func v410OpenshiftControllerManagerOldLeaderRolebindingYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerOldLeaderRolebindingYaml, nil
}

func v410OpenshiftControllerManagerOldLeaderRolebindingYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerOldLeaderRolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/old-leader-rolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerOpenshiftServiceCaCmYaml = []byte(`kind: ConfigMap
apiVersion: v1
metadata:
  name: openshift-service-ca
  namespace: openshift-controller-manager
  annotations: 
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
`)

func v410OpenshiftControllerManagerOpenshiftServiceCaCmYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerOpenshiftServiceCaCmYaml, nil
}

func v410OpenshiftControllerManagerOpenshiftServiceCaCmYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerOpenshiftServiceCaCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/openshift-service-ca-cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerSaYaml = []byte(`apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
`)

func v410OpenshiftControllerManagerSaYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerSaYaml, nil
}

func v410OpenshiftControllerManagerSaYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerSaYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/sa.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerSeparateSaRoleYaml = []byte(`# needed to support the "use separate service accounts" feature.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:openshift:sa-creating-openshift-controller-manager
  namespace: openshift-infra
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
`)

func v410OpenshiftControllerManagerSeparateSaRoleYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerSeparateSaRoleYaml, nil
}

func v410OpenshiftControllerManagerSeparateSaRoleYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerSeparateSaRoleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/separate-sa-role.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerSeparateSaRolebindingYaml = []byte(`# needed to support the "use separate service accounts" feature.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openshift-infra
  name: system:openshift:sa-creating-openshift-controller-manager
roleRef:
  kind: Role
  name: system:openshift:sa-creating-openshift-controller-manager
subjects:
- kind: ServiceAccount
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
`)

func v410OpenshiftControllerManagerSeparateSaRolebindingYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerSeparateSaRolebindingYaml, nil
}

func v410OpenshiftControllerManagerSeparateSaRolebindingYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerSeparateSaRolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/separate-sa-rolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerServicemonitorRoleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: openshift-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
`)

func v410OpenshiftControllerManagerServicemonitorRoleYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerServicemonitorRoleYaml, nil
}

func v410OpenshiftControllerManagerServicemonitorRoleYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerServicemonitorRoleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/servicemonitor-role.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerServicemonitorRolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
`)

func v410OpenshiftControllerManagerServicemonitorRolebindingYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerServicemonitorRolebindingYaml, nil
}

func v410OpenshiftControllerManagerServicemonitorRolebindingYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerServicemonitorRolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/servicemonitor-rolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerSvcYaml = []byte(`apiVersion: v1
kind: Service
metadata:
  namespace: openshift-controller-manager
  name: controller-manager
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: serving-cert
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    controller-manager: "true"
  ports:
  - name: https
    port: 443
    targetPort: 8443
`)

func v410OpenshiftControllerManagerSvcYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerSvcYaml, nil
}

func v410OpenshiftControllerManagerSvcYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerSvcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/svc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerTokenreviewClusterroleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:tokenreview-openshift-controller-manager
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
`)

func v410OpenshiftControllerManagerTokenreviewClusterroleYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerTokenreviewClusterroleYaml, nil
}

func v410OpenshiftControllerManagerTokenreviewClusterroleYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerTokenreviewClusterroleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/tokenreview-clusterrole.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v410OpenshiftControllerManagerTokenreviewClusterrolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:tokenreview-openshift-controller-manager
roleRef:
  kind: ClusterRole
  name: system:openshift:tokenreview-openshift-controller-manager
subjects:
- kind: ServiceAccount
  namespace: openshift-controller-manager
  name: openshift-controller-manager-sa
`)

func v410OpenshiftControllerManagerTokenreviewClusterrolebindingYamlBytes() ([]byte, error) {
	return _v410OpenshiftControllerManagerTokenreviewClusterrolebindingYaml, nil
}

func v410OpenshiftControllerManagerTokenreviewClusterrolebindingYaml() (*asset, error) {
	bytes, err := v410OpenshiftControllerManagerTokenreviewClusterrolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v4.1.0/openshift-controller-manager/tokenreview-clusterrolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"v4.1.0/openshift-controller-manager/cm.yaml":                             v410OpenshiftControllerManagerCmYaml,
	"v4.1.0/openshift-controller-manager/defaultconfig.yaml":                  v410OpenshiftControllerManagerDefaultconfigYaml,
	"v4.1.0/openshift-controller-manager/ds.yaml":                             v410OpenshiftControllerManagerDsYaml,
	"v4.1.0/openshift-controller-manager/informer-clusterrole.yaml":           v410OpenshiftControllerManagerInformerClusterroleYaml,
	"v4.1.0/openshift-controller-manager/informer-clusterrolebinding.yaml":    v410OpenshiftControllerManagerInformerClusterrolebindingYaml,
	"v4.1.0/openshift-controller-manager/leader-role.yaml":                    v410OpenshiftControllerManagerLeaderRoleYaml,
	"v4.1.0/openshift-controller-manager/leader-rolebinding.yaml":             v410OpenshiftControllerManagerLeaderRolebindingYaml,
	"v4.1.0/openshift-controller-manager/old-leader-role.yaml":                v410OpenshiftControllerManagerOldLeaderRoleYaml,
	"v4.1.0/openshift-controller-manager/old-leader-rolebinding.yaml":         v410OpenshiftControllerManagerOldLeaderRolebindingYaml,
	"v4.1.0/openshift-controller-manager/openshift-service-ca-cm.yaml":        v410OpenshiftControllerManagerOpenshiftServiceCaCmYaml,
	"v4.1.0/openshift-controller-manager/sa.yaml":                             v410OpenshiftControllerManagerSaYaml,
	"v4.1.0/openshift-controller-manager/separate-sa-role.yaml":               v410OpenshiftControllerManagerSeparateSaRoleYaml,
	"v4.1.0/openshift-controller-manager/separate-sa-rolebinding.yaml":        v410OpenshiftControllerManagerSeparateSaRolebindingYaml,
	"v4.1.0/openshift-controller-manager/servicemonitor-role.yaml":            v410OpenshiftControllerManagerServicemonitorRoleYaml,
	"v4.1.0/openshift-controller-manager/servicemonitor-rolebinding.yaml":     v410OpenshiftControllerManagerServicemonitorRolebindingYaml,
	"v4.1.0/openshift-controller-manager/svc.yaml":                            v410OpenshiftControllerManagerSvcYaml,
	"v4.1.0/openshift-controller-manager/tokenreview-clusterrole.yaml":        v410OpenshiftControllerManagerTokenreviewClusterroleYaml,
	"v4.1.0/openshift-controller-manager/tokenreview-clusterrolebinding.yaml": v410OpenshiftControllerManagerTokenreviewClusterrolebindingYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"v4.1.0": {nil, map[string]*bintree{
		"openshift-controller-manager": {nil, map[string]*bintree{
			"cm.yaml":                             {v410OpenshiftControllerManagerCmYaml, map[string]*bintree{}},
			"defaultconfig.yaml":                  {v410OpenshiftControllerManagerDefaultconfigYaml, map[string]*bintree{}},
			"ds.yaml":                             {v410OpenshiftControllerManagerDsYaml, map[string]*bintree{}},
			"informer-clusterrole.yaml":           {v410OpenshiftControllerManagerInformerClusterroleYaml, map[string]*bintree{}},
			"informer-clusterrolebinding.yaml":    {v410OpenshiftControllerManagerInformerClusterrolebindingYaml, map[string]*bintree{}},
			"leader-role.yaml":                    {v410OpenshiftControllerManagerLeaderRoleYaml, map[string]*bintree{}},
			"leader-rolebinding.yaml":             {v410OpenshiftControllerManagerLeaderRolebindingYaml, map[string]*bintree{}},
			"old-leader-role.yaml":                {v410OpenshiftControllerManagerOldLeaderRoleYaml, map[string]*bintree{}},
			"old-leader-rolebinding.yaml":         {v410OpenshiftControllerManagerOldLeaderRolebindingYaml, map[string]*bintree{}},
			"openshift-service-ca-cm.yaml":        {v410OpenshiftControllerManagerOpenshiftServiceCaCmYaml, map[string]*bintree{}},
			"sa.yaml":                             {v410OpenshiftControllerManagerSaYaml, map[string]*bintree{}},
			"separate-sa-role.yaml":               {v410OpenshiftControllerManagerSeparateSaRoleYaml, map[string]*bintree{}},
			"separate-sa-rolebinding.yaml":        {v410OpenshiftControllerManagerSeparateSaRolebindingYaml, map[string]*bintree{}},
			"servicemonitor-role.yaml":            {v410OpenshiftControllerManagerServicemonitorRoleYaml, map[string]*bintree{}},
			"servicemonitor-rolebinding.yaml":     {v410OpenshiftControllerManagerServicemonitorRolebindingYaml, map[string]*bintree{}},
			"svc.yaml":                            {v410OpenshiftControllerManagerSvcYaml, map[string]*bintree{}},
			"tokenreview-clusterrole.yaml":        {v410OpenshiftControllerManagerTokenreviewClusterroleYaml, map[string]*bintree{}},
			"tokenreview-clusterrolebinding.yaml": {v410OpenshiftControllerManagerTokenreviewClusterrolebindingYaml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
